// src/app/shared/navbar/navbar.component.ts
import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';
import { TuiIcon } from '@taiga-ui/core';
import { ThemeService } from '../../core/theme/theme.service';

@Component({
  selector: 'app-navbar',
  imports: [RouterLink, TuiIcon],
  templateUrl: './navbar.component.html',
})
export class NavbarComponent {
  constructor(public themeService: ThemeService) {}
}

<nav
  class="flex text-base sticky z-[1] top-0 shadow-md bg-white dark:bg-dark dark:border items-center justify-between py-4 px-6"
>
  <div class="flex gap-6 items-center">
    <a class="mr-2" routerLink="/">
      <img
        class="w-10 h-10 rounded-md"
        [src]="
          themeService.isLight()
            ? '/brands/logo_small.png'
            : '/brands/logo_white.png'
        "
        alt="logo"
      />
    </a>
    <a class="hover:underline dark:text-white" routerLink="/design">Design</a>
    <a class="hover:underline dark:text-white" routerLink="/about">About</a>
  </div>

  <div class="flex gap-4 items-center">
    <button
      class="hover:cursor-pointer mr-2"
      (click)="themeService.toggleTheme()"
    >
      <tui-icon
        [icon]="themeService.isLight() ? '@tui.moon' : '@tui.sun'"
        [style.color]="themeService.isLight() ? 'black' : 'white'"
      />
    </button>
    <button
      class="text-black bg-white ring ring-gray-300 px-4 py-2 rounded-md hover:bg-gray-100/90 hover:cursor-pointer"
      routerLink="/login"
    >
      Login
    </button>
    <button
      class="text-white bg-pitchdark px-4 py-2 rounded-md hover:bg-pitchdark/90 dark:hover:bg-gray-800/90 hover:cursor-pointer"
      routerLink="/register"
    >
      Join Us
    </button>
  </div>
</nav>

// components/shared/Navbar.tsx
import Link from "next/link";
import { Button, buttonVariants } from "@/components/ui/button";
import { SunIcon } from "lucide-react";

export const Navbar = () => {
  return (
    <nav className="flex sticky z-[1] top-0 border shadow-md bg-white items-center justify-between py-4 px-6">
      <Link href={"/"}>Logo</Link>
      <div className="flex gap-6 items-center">
        <Link className="hover:underline" href="/design">
          Design
        </Link>
        <Link className="hover:underline" href="/about">
          About
        </Link>
        <Button variant="outline" size="icon">
          <SunIcon />
        </Button>
        <Link
          className={`${buttonVariants({
            variant: "outline",
          })} py-2 px-4 border-2 rounded-md hover:bg-gray-50`}
          href="/login"
        >
          Login
        </Link>
      </div>
    </nav>
  );
};
